ADProjGp2_LogicUStationeryStore/Controllers/AdjustmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ADProjGp2_LogicUStationeryStore.BusinessLogic;
using ADProjGp2_LogicUStationeryStore.Models;

namespace ADProjGp2_LogicUStationeryStore.Controllers
{
    public class AdjustmentController : Controller
    {
        AdjustmentBusinessLogic adjBizLogic = new AdjustmentBusinessLogic();
        private static AdjustmentVoucherViewModel avvm;
        private static List<AdjustmentVoucherViewModelDetail> tempList;

        public ActionResult AdjustmentVoucherCreation()
        {
            avvm = adjBizLogic.InitiateAdjustmentVoucher(Session);
            tempList = new List<AdjustmentVoucherViewModelDetail>();
            avvm.itemList = tempList;        
            return View(avvm);
        }

        [HttpPost]
        public ActionResult AdjustmentVoucherCreation(string adjItem, string adjQty)
        {
            if (int.TryParse(adjQty, out int adjQtyTP))
            {
                adjBizLogic.AddItem(avvm, adjItem, adjQtyTP);
            }
            return View(avvm);
        }

        [HttpPost]
        public ActionResult ItemDelete(string adjItem)
        {
            adjBizLogic.DeleteItem(avvm, adjItem);
            return View("AdjustmentVoucherCreation", avvm);
        }

        [HttpPost]
        public ActionResult AdjustmentVoucherSave(AdjustmentVoucherViewModel avvmnew)
        {
            avvm = avvmnew;
            return View("AdjustmentVoucherCreation",avvm);
        }

        [HttpPost]
        public ActionResult AdjustmentVoucherConfirm(AdjustmentVoucherViewModel avvmnew)
        {
            adjBizLogic.CreateAdjustmentVoucher(avvmnew);
            return RedirectToAction("AdjustmentDetail", new { adjustmentID = avvm.voucherID });
        }

        public ActionResult AdjustmentDetail(string adjustmentID)
        {
            AdjustmentVoucherViewModel avvm = adjBizLogic.GetAdjustmentVoucher(adjustmentID, Session);
            return View(avvm);
        }
        
        public ActionResult AdjustmentHistory()
        {
            List<AdjustmentVoucherViewModel> avvmList = adjBizLogic.GetAdjustmentHistory(Session);
            avvmList.Sort(new AdjustmentComparerVoucherDate());
            return View(avvmList);
        }

        public ActionResult AdjustmentVoucherApprove(AdjustmentVoucherViewModel avvmnew)
        {
            avvm = adjBizLogic.ApproveVoucher(avvmnew);
            return View("AdjustmentVoucherCreation", avvm);
        }

    }
}

ADProjGp2_LogicUStationeryStore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using ADProjGp2_LogicUStationeryStore.Models;
using ADProjGp2_LogicUStationeryStore.BusinessLogic;
using System.Web.Security;

namespace ADProjGp2_LogicUStationeryStore.Controllers
{
    public class HomeController : Controller
    {
        CommonBusinessLogic commonBizLogic = new CommonBusinessLogic();
        public ActionResult Login()
        {
            return View(new LoginObjectModel());
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginObjectModel model)
        {
            if (ModelState.IsValid)
            {
                model = commonBizLogic.ValidateUser(model);
                //Login fail
                if (model is null)
                {
                    ViewBag.NotAuthorised = true;
                    return View();
                }
                Dictionary<string, string> empList = commonBizLogic.GetEmployeeList(model.userName, model.password, model.departmentId);
                commonBizLogic.PrepareSession(model, empList, Session);
                //currently testing using requisition history page
                return RedirectToAction("Welcome", "Home");
            }
            // Model State failed (basic validation), redisplay form  
            return View(model);
        }
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Session.Abandon(); // it will clear the session at the end of request
            return RedirectToAction("Login", "Home");
        }

        public ActionResult Welcome()
        {
            if(Session["Role"].ToString() == "clerk")
            {
                return RedirectToAction("ClerkWelcome");
            }
            else if (Session["Role"].ToString() == "supervisor")
            {
                return RedirectToAction("SupervisorWelcome");
            }
            else if (Session["Role"].ToString() == "manager")
            {
                return RedirectToAction("ManagerWelcome");
            }
            return View();
        }

        public ActionResult ClerkWelcome()
        {
            ClerkWelcomePageModel model = commonBizLogic.GetClerkWelcomePageModel(Session);
            return View(model);
        }
        public ActionResult SupervisorWelcome()
        {
            SupervisorWelcomePageModel model = commonBizLogic.GetSupervisorWelcomePageModel(Session);
            return View(model);
        }
        public ActionResult ManagerWelcome()
        {
            ManagerWelcomePageModel model = commonBizLogic.GetManagerWelcomePageModel(Session);
            return View(model);
        }

        public ActionResult ChangePassword()
        {
            return View(new ChangePasswordModel());
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult ChangePassword(ChangePasswordModel model)
        {
            if (ModelState.IsValid)
            {
                model = commonBizLogic.ChangePassword(model);
                //Login fail
                if (model.replymsg != "Password change success")
                { 
                    return View(model);
                }
                //currently testing using requisition history page
                return RedirectToAction("Login", "Home");
            }
            // Model State failed (basic validation), redisplay form  
            return View(model);
        }

        public ActionResult CPmap()
        {
            return View();
        }
    }
}

ADProjGp2_LogicUStationeryStore/Controllers/RequisitionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.ServiceModel.Web;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using ADProjGp2_LogicUStationeryStore.BusinessLogic;
using ADProjGp2_LogicUStationeryStore.Models;

namespace ADProjGp2_LogicUStationeryStore.Controllers
{
    public class RequisitionController : Controller
    {        
        private RequisitionBusinessLogic reqBizLogic = new RequisitionBusinessLogic();
        private CommonBusinessLogic commonBusinessLogic = new CommonBusinessLogic();
        private static RequisitionFormItemCart itemCart = new RequisitionFormItemCart();

        // New Requistion Form creation
        public ActionResult ReqForm()
        {
            if (TempData["INSession"] == null)
            {
                itemCart.RemoveAllCartItem();
            }
            return View(itemCart);
        }

        // Postback for adding items
        [HttpPost]
        public ActionResult ReqForm(string addItem, string addQty)
        {
            int x = 0;
            if (int.TryParse(addQty, out x))
            {
                itemCart.ItemCartAddDecision(addItem, x);
            }
            return View(itemCart);
        }

        // Deleting item
        public ActionResult Delete(int id)
        {
            itemCart.RemoveCartItem(id);
            TempData["INSession"] = true;
            return RedirectToAction("ReqForm");
        }

        //Triggers the requisition form packaging
        public ActionResult Generate()
        {
            //return on empty cart
            if (itemCart.RequestItemCart().Count()<=0)
                return RedirectToAction("ReqForm");

            return RedirectToAction("ReqFormSubmit");
        }

        //Pseudo-state page for requisition form submission - the final confirm
        public ActionResult ReqFormSubmit()
        {
            Requisition requisition = reqBizLogic.RequisitionFormGeneration(Session, itemCart);
            TempData["RequisitionFormGeneration"] = requisition;
            return View(requisition);
        }

        //Submission Actual - saving into DB
        public async Task<ActionResult> ReqFormSubmission()
        {
            Requisition requisition = (Requisition)TempData["RequisitionFormGeneration"];
            requisition = await reqBizLogic.SaveRequisitionForm(requisition, Session);
            TempData["RequisitionFormGeneration"] = requisition;
            return RedirectToAction("ReqFormDetail");
        }

        //Email notification to dept head about new submission
        public ActionResult ReqFromSubmitEmailNotification()
        {
            //Head to receive email
            return View();
        }

        // List of requisition for viewing
        public ActionResult RequisitionHistory()
        {
            List<Requisition> myReqList = reqBizLogic.MyRequisitionHistoryList(Session);
            myReqList.Sort(new RequisitionComparerApprovalDate());
            return View(myReqList);
        }

        // See Requisition Details
        public ActionResult ReqFormDetail(string id)
        {
            Requisition requisition = new Requisition();
            if (id == "" || id is null)
                requisition = (Requisition)TempData["RequisitionFormGeneration"];
            try
            {
                SSISEntities db = new SSISEntities();
                requisition = db.Requisitions.Where(x => x.requisitionId == id).First();
                if (requisition.RequisitionDetails == null)
                {
                    requisition = reqBizLogic.GetRequisitionDetails(requisition);
                }
            }
            catch (Exception e)
            {
                //log
            }
            return View(requisition);
        }

        //Requisition Approval
        public async Task<ActionResult> ReqApprove(Requisition requisition)
        {
            requisition = await reqBizLogic.ApproveRequisitionForm(requisition, Session);
            TempData["RequisitionFormGeneration"] = requisition;
            return RedirectToAction("ReqFormDetail");
        }

        public ActionResult ReqFromApproveEmailNotification()
        {
            //User to receive email
            return View();
        }

        //Requisition Rejection
        public async Task<ActionResult> ReqReject(Requisition requisition)
        {
            requisition = await reqBizLogic.RejectRequisitionForm(requisition, Session);
            TempData["RequisitionFormGeneration"] = requisition;
            return RedirectToAction("ReqFormDetail");
        }

        public ActionResult ReqFromRejectEmailNotification()
        {
            //User to receive email
            return View();
        }
    }
}

ADProjGp2_LogicUStationeryStore/Controllers/RetrievalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ADProjGp2_LogicUStationeryStore.Models;
using ADProjGp2_LogicUStationeryStore.BusinessLogic;
using System.Collections;
using System.Threading.Tasks;

namespace ADProjGp2_LogicUStationeryStore.Controllers
{
    public class RetrievalController : Controller
    {
        RetrievalBusinessLogic retrievalBizLogic = new RetrievalBusinessLogic();

        public ActionResult RetrievalListPreparation()
        {
            ModelState.Clear();
            List<ReqListSummary> list = retrievalBizLogic.CreateReqListSummaries();
            return View(list);
        }

        [HttpPost]
        public ActionResult RetrievalListPreparation(List<ReqListSummary> viewModel)
        {
            List<ReqListSummary> newList = new List<ReqListSummary>();
            if (viewModel != null)
            {
                newList = viewModel.Where(x => x.IsSelected == true).ToList<ReqListSummary>();
                return View(newList);
            }            
            return RedirectToAction("RetrievalListPreparation");
        }

        [HttpPost]
        public ActionResult RetrievalPreSave(List<ReqListSummary> retList)
        {
            ArrayList aList = new ArrayList();
            List <RetrievalListModel> retrievalList = new List<RetrievalListModel>();
            retList = retList.Where(x => x.IsSelected == true).ToList<ReqListSummary>();
            aList = retrievalBizLogic.GetRetrievalListModelsList(retrievalBizLogic.GetRequistions(retList));
            if (aList != null)
            {
                TempData["aList"] = aList;
            }
            else
            {
                List<ReqListSummary> tempReqList = retList.Where(x => x.IsSelected == true).ToList();
                TempData["tempRetList"] = tempReqList;
                return RedirectToAction("InventoryInsufficient");
            }
            return RedirectToAction("RetrievalSave");
        }

        public ActionResult InventoryInsufficient()
        {
            List<ReqListSummary> tempReqList = (List<ReqListSummary>)TempData["tempRetList"];
            List<InsufficientStockModel> model = retrievalBizLogic.GenerateInsufficientStockModels(tempReqList);
            return View(model);
        }

        public ActionResult RetrievalSave(List<RetrievalListModel> retrievalList)
        {
            ArrayList aList = new ArrayList();            
            if(TempData["aList"] != null)
            {
                aList = (ArrayList)TempData["aList"];
                retrievalList = (List<RetrievalListModel>)aList[0];
                ViewBag.retSum = (List<RetrievalListSummaryModel>)aList[1];
                return View(retrievalList);
            }
            string clerkID = Session["EmployeeID"].ToString();
            retrievalBizLogic.SaveRetrievalList(retrievalList, clerkID);
            List<RetrievalListSummaryModel> retSumModel = retrievalBizLogic.RetrievalListSumModelGeneration(retrievalList);
            aList = retrievalBizLogic.RetrievalGenerationViewModel(retrievalList, retSumModel);
            retrievalList = (List<RetrievalListModel>)aList[0];
            ViewBag.retSum = (List<RetrievalListSummaryModel>)aList[1];
            return View(retrievalList);
        }

        [HttpPost]
        public async Task<ActionResult> ConfirmRetrievalList(List<RetrievalListModel> retrievalList)
        {
            string clerkID = Session["EmployeeID"].ToString();
            retrievalBizLogic.SaveRetrievalList(retrievalList, clerkID);
            bool haveWarning = retrievalBizLogic.CheckRetrievalSubmissionWarning(retrievalList);
            if(haveWarning)
            {
                List<RetrievalListSummaryModel> rsm = retrievalBizLogic.RetrievalListSumModelGeneration(retrievalList);
                ArrayList aList = retrievalBizLogic.RetrievalGenerationViewModel(retrievalList, rsm);
                TempData["aList"] = aList;
                return RedirectToAction("RetrievalSave");
            }
            retrievalBizLogic.ConfirmRetrievalList(retrievalList, clerkID);
            List<RetrievalListSummaryModel> retSumModel = retrievalBizLogic.RetrievalListSumModelGeneration(retrievalList);
            DisbursementBusinessLogic disburseBizLogic = new DisbursementBusinessLogic();
            await disburseBizLogic.DisbursementAllocation(retrievalList, Session);
            ViewBag.retSum = retSumModel;
            return View(retrievalList);
        }

        public ActionResult RetrievalHistory()
        {
            List<RetListSummary> history = retrievalBizLogic.GetRetrievalListHistory();
            history.Sort(new RetListComparerByCreateDate());
            return View(history);
        }

        public ActionResult RetrievalDetail(string retrievalListID)
        {
            ArrayList aList = new ArrayList();
            List<RetrievalListModel> retrievalList = new List<RetrievalListModel>();
            aList = retrievalBizLogic.GetRetrievalListDetail(retrievalListID);
            retrievalList = (List<RetrievalListModel>)aList[0];
            ViewBag.retSum = (List<RetrievalListSummaryModel>)aList[1];
            ViewBag.DisburseCheck = retrievalBizLogic.CheckRetrievalDetailDisbursementStatus(retrievalList);
            return View(retrievalList);
        }

        public ActionResult RetrievalPending(string retrievalListID)
        {
            ArrayList aList = new ArrayList();
            List<RetrievalListModel> retrievalList = new List<RetrievalListModel>();
            aList = retrievalBizLogic.GetRetrievalListDetail(retrievalListID);
            TempData["aList"] = aList;
            return RedirectToAction("RetrievalSave");
        }

        public ActionResult ReqIDsPopup()
        {
            List<RetListSummary> list = retrievalBizLogic.GetRetrievalListHistory();
            return View(list);
        }
    }
}

ADProjGp2_LogicUStationeryStore/Views/Home/CPmap.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CPmap</title>
</head>
<body>
    <div> 
        <img src="~/Content/images/CPmapWithRemark.jpg"/>
    </div>
</body>
</html>

ADProjGp2_LogicUStationeryStore/Views/Home/ClerkWelcome.cshtml
@{
    ViewBag.Title = "Welcome";
}


@model ADProjGp2_LogicUStationeryStore.Models.ClerkWelcomePageModel
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Clerk Welcome</title>
    <link href="~/Content/css/Button-Antiman.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/css/Requisition.css" rel="stylesheet" type="text/css" />
    <style>

        table thead, table tr {
            /*border-top-width: 1px;
            border-top-style: solid;
            border-top-color: #808080;*/
        }

        table tbody th {
            /*background-color: #d6dfe5;*/
            background-color: rgba(214, 223, 229, 0.30);
            padding-left: 10px;
            text-align: center;
        }

        table tbody td {
            padding-left: 8px;
            padding-right: 8px;
        }

        table {
            /*border-bottom-width: 1px;
            border-bottom-style: solid;
            border-bottom-color: #808080;
            border-left-width: 1px;
            border-left-style: solid;
            border-left-color: #808080;
            border-right-width: 1px;
            border-right-style: solid;
            border-right-color: #808080;*/
            table-layout: fixed;
            width: 80%;
            position: relative;
            margin: auto;
            text-align: center;
            margin-bottom: 15px;
            font-size: medium;
            min-width: 660px;
        }

        b{
            color:coral;
        }

        fieldset {
            position: relative;
            padding: 15px;
            margin: 10px 12.5%;
            width: 75%;
            color: #333;
            border: #06c dashed 1px;
            min-width:755px;

        }
        legend {
            color: #06c;
            font-weight: 800;
            background: #fff;
            padding: 3px 6px;
            width:auto;
            border-bottom:none;
        } 
    </style>
</head>
<body>
    <h2 style="padding-left:20px;">  Welcome @Session["DepartmentID"].ToString() > @Session["Role"].ToString() >@Session["EmployeeName"].ToString()</h2>
    <br />


    @if (Model.RequisitionWPC.Count > 0)
    {
        using (@Html.BeginForm())
        {
            <div>
                <fieldset>
                    <legend><span>You have <b>Requistions</b> awaiting your action</span></legend>
                    <table class="table-hover">
                        <tr>
                            <th>Requistion ID </th>
                            <th>Approval Date</th>
                        </tr>
                        @for (int i = 0; i < Model.RequisitionWPC.Count; i++)
                    {
                            <tr>
                                <td>@Html.ActionLink(Model.RequisitionWPC[i].RequisitionID, "ReqFormDetail", "Requisition", new { id = Model.RequisitionWPC[i].RequisitionID }, new { @style = "text-decoration:underline;" })</td>
                                @Html.HiddenFor(m => m.RequisitionWPC[i].RequisitionID)
                                <td>@Model.RequisitionWPC[i].RequisitionApproveDate</td>
                                @Html.HiddenFor(m => m.RequisitionWPC[i].RequisitionApproveDate)
                            </tr>
                        }
                    </table>
                </fieldset>
            </div>
        }
    }
    else
    {
        <h3>You have no Requistion Form awaiting your action.</h3>
    }


    <br />

    @if (Model.RetrievalWPC.Count > 0)
    {
        using (@Html.BeginForm())
        {
            <div>
                <fieldset>
                    <legend>You have saved <b>Retrieval Forms</b> awaiting your confirmation</legend>
                    <table class="table-hover">
                        <tr>
                            <th>Retrieval ID </th>
                            <th>Saved Date</th>
                        </tr>
                        @for (int i = 0; i < Model.RetrievalWPC.Count; i++)
                    {
                            <tr>
                                <td>@Html.ActionLink(Model.RetrievalWPC[i].RetrievalID, "RetrievalDetail", "Retrieval", new { retrievalListID = Model.RetrievalWPC[i].RetrievalID }, new { @style = "text-decoration:underline;" })</td>
                                @Html.HiddenFor(m => m.RetrievalWPC[i].RetrievalID)
                                <td>@Model.RetrievalWPC[i].RetrievalCreationDate</td>
                                @Html.HiddenFor(m => m.RetrievalWPC[i].RetrievalCreationDate)
                            </tr>
                        }
                    </table>

                </fieldset>
            </div>
        }
    }
    else
    {
        <h3>You have no Retrieval Form awaiting your action.</h3>
    }


    <br />

    @if (Model.DisbursementWPC.Count > 0)
    {
        using (@Html.BeginForm())
        {
            <div>
                <fieldset>
                    <legend>You have <b>Disbursement Lists</b> awaiting delivery for user collection</legend>
                    <table class="table-hover">
                        <tr>
                            <th>Disbursement ID </th>
                            <th>Disbursement Creation Date</th>
                            <th>Disbursement Collection Point</th>
                            <th>Disbursement Collection Date</th>
                        </tr>
                        @for (int i = 0; i < Model.DisbursementWPC.Count; i++)
                    {
                            <tr>
                                <td>@Html.ActionLink(Model.DisbursementWPC[i].DisbursementID, "WelcomeDisburseIDRedirection", "Disbursement", new { disburseID = Model.DisbursementWPC[i].DisbursementID, retID = Model.DisbursementWPC[i].DisbursementRetID }, new { @style = "text-decoration:underline;" })</td>
                                @Html.HiddenFor(m => m.DisbursementWPC[i].DisbursementID)
                                @Html.HiddenFor(m => m.DisbursementWPC[i].DisbursementRetID)
                                <td>@Model.DisbursementWPC[i].DisbursementCreationDate</td>
                                @Html.HiddenFor(m => m.DisbursementWPC[i].DisbursementCreationDate)
                                <td>@Model.DisbursementWPC[i].DisburementCollectionPoint</td>
                                @Html.HiddenFor(m => m.DisbursementWPC[i].DisburementCollectionPoint)
                                <td>@Model.DisbursementWPC[i].DisbursementCollectDate</td>
                                @Html.HiddenFor(m => m.DisbursementWPC[i].DisbursementCollectDate)
                            </tr>
                        }
                    </table>
                </fieldset>
            </div>
        }
    }
    else
    {
        <h3>You have no Disbursement List to deliver.</h3>
    }

    <br />

    @if (Model.AdjustmentWPC.Count > 0)
    {
        using (@Html.BeginForm())
        {
            <div>
                <fieldset>
                    <legend>You have <b>Adjustment Vouchers</b> awaiting approval</legend>
                    <table class="table-hover">
                        <tr>
                            <th>Adjustment ID </th>
                            <th>Adjustment Date</th>
                        </tr>
                        @for (int i = 0; i < Model.AdjustmentWPC.Count; i++)
                    {
                            <tr>
                                <td>@Html.ActionLink(Model.AdjustmentWPC[i].AdjustmentID, "AdjustmentDetail", "Adjustment", new { adjustmentID = Model.AdjustmentWPC[i].AdjustmentID }, new { @style = "text-decoration:underline;" })</td>
                                @Html.HiddenFor(m => m.AdjustmentWPC[i].AdjustmentID)
                                <td>@Model.AdjustmentWPC[i].AdjustmentDate</td>
                                @Html.HiddenFor(m => m.AdjustmentWPC[i].AdjustmentDate)
                            </tr>
                        }
                    </table>
                </fieldset>

            </div>
        }
    }
    else
    {
        <h3>You have no pending Adjustment Voucher.</h3>
    }


    <br />

    @if (Model.StockWPC.Count > 0)
    {
        using (@Html.BeginForm())
        {
            <div>
                <fieldset>
                    <legend>The following items are in <strong style="color:red;">low stock level</strong> --> <a href="~/Purchase/NewPurchaseOrder" style="text-decoration:underline;">Purchase Now</a></legend>
                    <table class="table-hover">
                        <tr>
                            <th>Item Name & ID</th>
                            <th>Item Current Stock Qty</th>
                            <th>Item Reorder Level</th>
                            @*<th>Any Purchase incoming?</th>*@
                            <th>Incoming Qty (if any)</th>
                        </tr>
                        @for (int i = 0; i < Model.StockWPC.Count; i++)
                    {
                            <tr>
                                <td>@Model.StockWPC[i].ItemDescription (@Model.StockWPC[i].ItemID)</td>
                                @Html.HiddenFor(m => m.StockWPC[i].ItemDescription)
                                @Html.HiddenFor(m => m.StockWPC[i].ItemID)
                                <td>@Model.StockWPC[i].qtyStock</td>
                                @Html.HiddenFor(m => m.StockWPC[i].qtyStock)
                                <td>@Model.StockWPC[i].qtyReorderLevel</td>
                                @Html.HiddenFor(m => m.StockWPC[i].qtyReorderLevel)
                                @*<td>@Model.StockWPC[i].PurchaseOrderID</td>*@
                                @Html.HiddenFor(m => m.StockWPC[i].PurchaseOrderID)
                                <td>@Model.StockWPC[i].purchaseQty</td>
                                @Html.HiddenFor(m => m.StockWPC[i].purchaseQty)
                            </tr>
                        }
                    </table>
                </fieldset>
            </div>
        }
    }
    else
    {
        <h3>There is no stock that is under the reorder level.</h3>
    }

    <br />
</body>
</html>

ADProjGp2_LogicUStationeryStore/Views/Home/ManagerWelcome.cshtml
@{
    ViewBag.Title = "Welcome";
}


@model ADProjGp2_LogicUStationeryStore.Models.ManagerWelcomePageModel
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Disbursement List Summary</title>
    <link href="~/Content/css/Button-Antiman.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/css/Requisition.css" rel="stylesheet" type="text/css" />
    <style>
        table thead, table tr {
            /*border-top-width: 1px;
        border-top-style: solid;
        border-top-color: #808080;*/
        }

        table tbody th {
            /*background-color: #d6dfe5;*/
            background-color: rgba(214, 223, 229, 0.30);
            padding-left: 10px;
            text-align: center;
        }

        table tbody td {
            padding-left: 8px;
            padding-right: 8px;
        }

        table {
            /*border-bottom-width: 1px;
        border-bottom-style: solid;
        border-bottom-color: #808080;
        border-left-width: 1px;
        border-left-style: solid;
        border-left-color: #808080;
        border-right-width: 1px;
        border-right-style: solid;
        border-right-color: #808080;*/
            table-layout: fixed;
            width: 80%;
            position: relative;
            margin: auto;
            text-align: center;
            margin-bottom: 15px;
            font-size: medium;
            min-width: 660px;
        }

        b {
            color: coral;
        }

        fieldset {
            position: relative;
            padding: 15px;
            margin: 10px 12.5%;
            width: 75%;
            color: #333;
            border: #06c dashed 1px;
            min-width: 755px;
        }

        legend {
            color: #06c;
            font-weight: 800;
            background: #fff;
            padding: 3px 6px;
            width: auto;
            border-bottom: none;
        }
    </style>
</head>
<body>
    <h2 style="padding-left:20px;">  Welcome @Session["DepartmentID"].ToString() > @Session["Role"].ToString() >@Session["EmployeeName"].ToString()</h2>

    <br />

    @if (Model.AdjustmentWPC.Count > 0)
    {
        using (@Html.BeginForm())
        {
            <div>
                <fieldset>
                    <legend>You have <b>Adjustment Vouchers</b> awaiting approval</legend>
                    <table class="table-hover">
                        <tr>
                            <th>Adjustment ID </th>
                            <th>Adjustment Date</th>
                        </tr>
                        @for (int i = 0; i < Model.AdjustmentWPC.Count; i++)
                    {
                            <tr>
                                <td>@Html.ActionLink(Model.AdjustmentWPC[i].AdjustmentID, "AdjustmentDetail", "Adjustment", new { adjustmentID = Model.AdjustmentWPC[i].AdjustmentID }, new { @style = "text-decoration:underline;" })</td>
                                @Html.HiddenFor(m => m.AdjustmentWPC[i].AdjustmentID)
                                <td>@Model.AdjustmentWPC[i].AdjustmentDate</td>
                                @Html.HiddenFor(m => m.AdjustmentWPC[i].AdjustmentDate)
                            </tr>
                        }
                    </table>

                </fieldset>
            </div>
        }
    }
    else
    {
        <h3>You have no adjustment vouchers pending</h3>
    }

</body>
</html>

ADProjGp2_LogicUStationeryStore/Views/Home/Welcome.cshtml
@{
    ViewBag.Title = "Welcome";
}

<h2>  Welcome @Session["DepartmentID"].ToString() > @Session["Role"].ToString() > @Session["username"].ToString()</h2>