ADProjGp2_LogicUStationeryStore/Controllers/ReorderReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ADProjGp2_LogicUStationeryStore.Models;
using ADProjGp2_LogicUStationeryStore.BusinessLogic;

namespace ADProjGp2_LogicUStationeryStore.Controllers
{
    public class ReorderReportController : Controller
    {
        // GET: ReorderReport
        ReorderReportBusinessLogic roBL = new ReorderReportBusinessLogic();
        ReportBusinessLogic rBL = new ReportBusinessLogic();

        string[] color = new string[12] { "#999999", "#E9967A", "#CD5C5C", "#1A5276", "#27AE60", "#FF0000", "#800000", "#808000", "#008080", "#800080", "#0000FF", "#000080", };
        string[] border = new string[12] { "#999999", "#E9967A", "#CD5C5C", "#1A5276", "#27AE60", "#FF0000", "#800000", "#808000", "#008080", "#800080", "#0000FF", "#000080" };
        string[] months = new string[12] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" };

        public ActionResult AnnualPurchaseReport()
        {

            ReorderChartModel rm = new ReorderChartModel()
            {
                YearSelection = rBL.DisplayYears(),
                SelectedYear = "All",                         //Add this
            };

            return View(rm);
        }

        public JsonResult AnnualReorderData(ReorderChartModel rm)
        {
            Chartjs _chart = new Chartjs();

            _chart.labels = new string[] { };

            _chart.datasets = new List<Datasets>();
            List<Datasets> _dataSet = new List<Datasets>();

            if (rm.SelectedYear == "All")
            {
                List<string> years = new List<string>();
                for (int i = 3; i >= 1; i--)
                {
                    years.Add(rm.YearSelection[i].Value);
                }
                _chart.labels = years.ToArray();


              

                _dataSet.Add(new Datasets()
                {
                    label = "Stationery Reorder Quantity",
                    data = roBL.GetItems(),
                    backgroundColor = new string[] { "#6B7ABB", "#6B7ABB", "#6B7ABB" },
                    borderColor = new string[] { "#6B7ABB", "#6B7ABB", "#6B7ABB" },
                    borderWidth = "1"
                });

                _chart.datasets = _dataSet;
            }
            else
            {
                _chart.labels = months;
               
                List<string> colors = new List<string>();
                List<string> borders = new List<string>();

                for (int i = 0; i < 13; i++)
                {
                    colors.Add("#1A5276");
                    borders.Add("#1A5276");
                }

                _dataSet.Add(new Datasets()
                {
                    label = "Stationery Reorder Quantity",
                    data = roBL.GetItemsMonthly(rm.SelectedYear),
                    backgroundColor = colors.ToArray(),
                    borderColor = borders.ToArray(),
                    borderWidth = "1"
                });

                _chart.datasets = _dataSet;


            }

            return Json(_chart, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ReorderReportBySupplier()
        {


            ReorderChartModel rm = new ReorderChartModel()
            {
                Items = rBL.DisplayItems(),
                YearSelection = rBL.DisplayYears(),
                Months = rBL.DisplayMonths(),
                Suppliers = roBL.DisplaySuppliers(),
                SelectedItem = "All",

            };

            return View(rm);
        }

        public JsonResult ReorderDataBySup(ReorderChartModel rm)
        {
            Chartjs _chart = new Chartjs();
            _chart.datasets = new List<Datasets>();
            List<Datasets> _dataSet = new List<Datasets>();

            _chart.labels = new string[] { };
            List<string> labels = new List<string>();



            List<string> selectedSupplier = new List<string>();
            for (int i = 0; i < rm.Suppliers.Count; i++)
            {
                if (rm.Suppliers[i].Selected)
                {
                    selectedSupplier.Add(rm.Suppliers[i].Value);
                }
            }

            rm.YearSelection = rBL.DisplayYears();
            List<string> years = new List<string>();
            for (int i = 3; i >= 1; i--)
            {
                years.Add(rm.YearSelection[i].Value);
            }

            if (rm.Months[0].Selected)
            {

                _chart.labels = years.ToArray();

                if (rm.SelectedItem == "All")
                {
                    for (int i = 0; i < selectedSupplier.Count; i++)
                    {
                        List<string> colors = new List<string>();
                        List<string> borders = new List<string>();
                        Dictionary<string, int> supplierOrder = roBL.GetTotalBySupplier(selectedSupplier[i], years);
                        List<int> listData = new List<int>();

                        foreach (KeyValuePair<string, int> pair in supplierOrder)
                        {
                            for (int j = 0; j < years.Count; j++)
                            {
                                if (pair.Key == years[j])
                                {
                                    listData.Add(pair.Value);
                                    colors.Add(color[i]);
                                    borders.Add(color[i]);
                                }
                            }

                        }

                        _dataSet.Add(new Datasets()
                        {
                            label = selectedSupplier[i],
                            data = listData.ToArray(),
                            backgroundColor = colors.ToArray(),
                            borderColor = borders.ToArray(),
                            borderWidth = "1"
                        });

                    }
                }
                else
                {

                    for (int i = 0; i < selectedSupplier.Count; i++)
                    {
                        Dictionary<string, int> supplierOrder = roBL.GetTotalBySupplier(selectedSupplier[i], rm.SelectedItem, years);
                        List<int> listData = new List<int>();
                        List<string> colors = new List<string>();
                        List<string> borders = new List<string>();

                        foreach (KeyValuePair<string, int> pair in supplierOrder)
                        {
                            for (int j = 0; j < years.Count; j++)
                            {
                                if (pair.Key == years[j])
                                {
                                    listData.Add(pair.Value);
                                    colors.Add(color[i]);
                                    borders.Add(border[i]);
                                }

                            }
                        }
                        _dataSet.Add(new Datasets()
                        {
                            label = selectedSupplier[i],
                            data = listData.ToArray(),
                            backgroundColor = colors.ToArray(),
                            borderColor = borders.ToArray(),
                            borderWidth = "1"
                        });

                    }

                }
            }

            else
            {
                List<int> currentYear = new List<int>();
                List<int> lastYear = new List<int>();
                List<int> previousYear = new List<int>();

                for (int i = 25; i <= 36; i++)
                {
                    if (rm.Months[i].Selected)
                    {
                        previousYear.Add(i - 24);
                        labels.Add(months[i - 25] + " " + years[0]);
                    }
                }
                for (int i = 13; i <= 24; i++)
                {
                    if (rm.Months[i].Selected)
                    {

                        lastYear.Add(i - 12);
                        labels.Add(months[i - 13] + " " + years[1]);
                    }
                }
                for (int i = 1; i <= 12; i++)
                {
                    if (rm.Months[i].Selected)
                    {
                        currentYear.Add(i);
                        labels.Add(months[i - 1] + " " + years[2]);
                    }
                }



                if (rm.SelectedItem == "All")
                {
                    for (int i = 0; i < selectedSupplier.Count; i++)
                    {
                        List<int> listData = new List<int>();
                        List<string> colors = new List<string>();
                        List<string> borders = new List<string>();

                        Dictionary<int, int> orderPreviousYear = roBL.GetTotalBySuppAndYear(selectedSupplier[i], years[0], previousYear);
                        foreach (KeyValuePair<int, int> pair in orderPreviousYear)
                        {
                            listData.Add(pair.Value);
                            colors.Add(color[i]);
                            borders.Add(border[i]);
                        }

                        Dictionary<int, int> orderLastYear = roBL.GetTotalBySuppAndYear(selectedSupplier[i], years[1], lastYear);
                        foreach (KeyValuePair<int, int> pair in orderLastYear)
                        {

                            listData.Add(pair.Value);
                            colors.Add(color[i]);
                            borders.Add(border[i]);
                        }

                        Dictionary<int, int> orderCurrentYear = roBL.GetTotalBySuppAndYear(selectedSupplier[i], years[2], currentYear);

ADProjGp2_LogicUStationeryStore/Views/ReorderReport/AnnualPurchaseReport.cshtml
@model ADProjGp2_LogicUStationeryStore.Models.ReorderChartModel
@{
        ViewBag.Title = "AnnualPurchaseReport";
    }

    <h3>Annual Purchase Report</h3>
    <div class="col-lg-12">
        <div class="row">
            <div class="form-group">


                @using (Ajax.BeginForm("AnnualReorderData", "ReorderReport", new AjaxOptions { HttpMethod = "POST", OnSuccess = "formSuccess" }))

                {
                    <div class="panel panel-default">

                        <div class="panel-heading" role="tab" id="headingOne">
                            <h4 class="panel-title">
                                <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                    Select Year
                                </a>
                            </h4>
                        </div>
                        <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                            <div class="panel-body">

                                <table>

                                    @*set maximum selection*@
                                    <tr>
                                        @for (var i = 0; i < Model.YearSelection.Count; i++)
                                        {
                                            <td width="10%">
                                                @Html.RadioButtonFor(m => Model.SelectedYear, Model.YearSelection[i].Value)
                                                @Html.DisplayFor(m => Model.YearSelection[i].Value)
                                                @Html.HiddenFor(m => Model.YearSelection[i].Value)
                                            </td>
                                        }

                                </table>
                            </div>
                        </div>
                    </div>

                    <button type="submit"
                            class="btn btn-primary"
                            id="process"
                            value="Process">
                        <span class="ladda-label">Generate Report</span>
                    </button>


                }
                <div id="graph">
                    <canvas id="barChart" width="400" height="150"></canvas>
                </div>


            </div>
        </div>

    </div>

    @section scripts {
        <script src="~/Scripts/Chart.js"></script>
        <script src="~/Scripts/jquery-1.10.2.js"></script>
       
        <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
        <script>

            var myBarChart = '';
            function formSuccess(data) {
                var c = document.getElementById("barChart");
                var ctx = c.getContext("2d");
                var tData = data;

                if (myBarChart) myBarChart.destroy(); {
                    myBarChart = new Chart(ctx, {
                        type: 'bar',
                        data: tData
                    });
                }
            }
        </script>
    }

ADProjGp2_LogicUStationeryStore/Views/ReorderReport/ReorderReportBySupplier.cshtml
@model ADProjGp2_LogicUStationeryStore.Models.ReorderChartModel
@{
    ViewBag.Title = "ReorderReportBySupplier";
}

<h2>Reorder Report</h2>
<div class="col-lg-12">
    <div class="row">
        <div class="form-group">


            @using (Ajax.BeginForm("ReorderDataBySup", "ReorderReport", new AjaxOptions { HttpMethod = "POST", OnSuccess = "formSuccess" }))

            {
                <div class="panel panel-default">

                    <div class="panel-heading" role="tab" id="headingOne">
                        <h4 class="panel-title">
                            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                Select Stationery
                            </a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                        <div class="panel-body">

                            <table>

                                @*set maximum selection*@
                                <tr>
                                    @for (var i = 0; i < 10; i++)
                                    {
                                        <td width="10%">
                                            @Html.RadioButtonFor(m => Model.SelectedItem, Model.Items[i].Value)
                                            @Html.DisplayFor(m => Model.Items[i].Value)
                                            @*Html.HiddenFor(m => Model.Items[i].Value*@


                                            @*Html.ListBoxFor(m => Model.SelectedCat, new MultiSelectList(Model.Items, "Value", "Text", Model.SelectedCat), new { @class = "form-control", style = "height:250px; width:100%" })*@
                                        </td>
                                    }
                                <tr>
                                    @for (var i = 10; i < Model.Items.Count; i++)
                                    {
                                        <td width="10%">
                                            @Html.RadioButtonFor(m => Model.SelectedItem, Model.Items[i].Value)
                                            @Html.DisplayFor(m => Model.Items[i].Value)
                                            @*Html.HiddenFor(m => Model.Items[i].Value)*@


                                        </td>
                                    }
                                </tr>
                            </table>
                        </div>

                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="headingTwo">
                        <h4 class="panel-title">
                            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                Select Suppliers
                            </a>
                        </h4>
                    </div>
                    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                        <div class="panel-body">
                            <p class=" instruction" style="color:brown">Please select up to three suppliers only</p>
                            <table>

                                @*set maximum selection*@
                                <tr>
                                    @for (var i = 0; i < Model.Suppliers.Count; i++)
                                    {
                                        <td width="10%">
                                            @Html.CheckBoxFor(m => Model.Suppliers[i].Selected, new { @class = "suppliers" })
                                            @Html.DisplayFor(m => Model.Suppliers[i].Value)
                                            @Html.HiddenFor(m => Model.Suppliers[i].Value)


                                            @*Html.ListBoxFor(m => Model.SelectedCat, new MultiSelectList(Model.Items, "Value", "Text", Model.SelectedCat), new { @class = "form-control", style = "height:250px; width:100%" })*@
                                        </td>
                                    }
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="headingThree">
                        <h4 class="panel-title">
                            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                Select Months to Compare (Up to 3 years)
                            </a>
                        </h4>
                    </div>
                    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                        <div class="panel-body">

                            <p class=" instruction" style="color:brown">Please select "Comparison for three years" or up to 6 months only</p>

                            <p>

                                @Html.CheckBoxFor(m => Model.Months[0].Selected, new { @class = "year" })
                                @Html.DisplayFor(m => Model.Months[0].Value)
                                @Html.HiddenFor(m => Model.Months[0].Value)

                            </p>


                            <table>


                                <tr>

                                    Select Months (@Model.YearSelection[1].Value):

                                </tr>

                                <tr>
                                    @for (var i = 1; i < 7; i++)
                                    {
                                        <td width="5%">
                                            @Html.CheckBoxFor(m => Model.Months[i].Selected, new { @class = "year" })
                                            @Html.DisplayFor(m => Model.Months[i].Value)
                                            @Html.HiddenFor(m => Model.Months[i].Value)

                                        </td>
                                    }
                                </tr>
                                <tr>
                                    @for (var i = 7; i < 13; i++)
                                    {
                                        <td width="5%">
                                            @Html.CheckBoxFor(m => Model.Months[i].Selected, new { @class = "year" })
                                            @Html.DisplayFor(m => Model.Months[i].Value)
                                            @Html.HiddenFor(m => Model.Months[i].Value)
                                            @Html.HiddenFor(m => Model.Months[i].Text)
                                        </td>
                                    }
                                </tr>
                            </table>
                            <table>
                                <tr>

                                    Select Months (@Model.YearSelection[2].Value):

                                </tr>
                                <tr>
                                    @for (var i = 13; i < 19; i++)
                                    {
                                        <td width="18.4%">
                                            @Html.CheckBoxFor(m => Model.Months[i].Selected, new { @class = "year" })
                                            @Html.DisplayFor(m => Model.Months[i].Value)
                                            @Html.HiddenFor(m => Model.Months[i].Value)
                                        </td>
                                    }
                                </tr>
                                <tr>
                                    @for (var i = 19; i < 25; i++)
                                    {
                                        <td width="18.4%">
                                            @Html.CheckBoxFor(m => Model.Months[i].Selected, new { @class = "year" })
                                            @Html.DisplayFor(m => Model.Months[i].Value)
                                            @Html.HiddenFor(m => Model.Months[i].Value)
                                        </td>
                                    }
                                </tr>
                            </table>
                            <div>
                                <table>
                                    <tr>

                                        Select Months (@Model.YearSelection[3].Value):

                                    </tr>
                                    <tr>
                                        @for (var i = 25; i < 31; i++)
                                        {
                                            <td width="18.4%">
                                                @Html.CheckBoxFor(m => Model.Months[i].Selected, new { @class = "year" })
                                                @Html.DisplayFor(m => Model.Months[i].Value)
                                                @Html.HiddenFor(m => Model.Months[i].Value)
                                            </td>
                                        }
                                    </tr>
                                    <tr>
                                        @for (var i = 31; i < Model.Months.Count; i++)
                                        {
                                            <td width="18.4%">
                                                @Html.CheckBoxFor(m => Model.Months[i].Selected, new { @class = "year" })
                                                @Html.DisplayFor(m => Model.Months[i].Value)
                                                @Html.HiddenFor(m => Model.Months[i].Value)
                                            </td>
                                        }
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>



                <button type="submit"
                        class="btn btn-primary"
                        id="process"
                        value="Process">
                    <span class="ladda-label">Generate Report</span>
                </button>



            }

            <div id="graph">
                <canvas id="barChart" width="400" height="150"></canvas>
            </div>

        </div>
    </div>
</div>

@section scripts {
    <script src="~/Scripts/Chart.js"></script>
    <script src="~/Scripts/jquery-1.10.2.js"></script>

    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>


    <script>
                    var coll = document.getElementsByClassName("collapsible");
                    var i;

                    for (i = 0; i < coll.length; i++) {
                        coll[i].addEventListener("click", function () {
                            this.classList.toggle("active");
                            var content = this.nextElementSibling;
                            if (content.style.display === "block") {
                                content.style.display = "none";
                            } else {
                                content.style.display = "block";
                            }
                        });
        }





        $(".suppliers").on('change', disableWithMax);

        function disableWithMax() {
                if ($("." + this.className + ":checked").length > 3) {
                    this.checked = false;
                    //alert("Maximum selection is 3 only");
                }

        }

        $(".year").on('change', disableOthers);

        function disableOthers() {
            if ($("." + this.className).eq(0).is(':checked')) {
                for (var i = 1; i < 37; i++) {
                    $("." + this.className).eq(i).attr('disabled', true);
                    $("." + this.className).eq(i).attr('checked', false);
                }
            }
            else {
                for (var i = 1; i < 37; i++) {
                 $("." + this.className).eq(i).attr('disabled', false);

                        if ($("." + this.className + ":checked").length > 6) {
                            this.checked = false;
                        }
                }
            }

        }

        var myBarChart = '';
        function formSuccess(data) {
            var c = document.getElementById("barChart");

            var ctx = c.getContext("2d");
            var tData = data;
            if (myBarChart) myBarChart.destroy();
                myBarChart = new Chart(ctx, {
                    type: 'bar',
                    data: tData

                });

        }


    </script>
}