ADProjGp2_LogicUStationeryStore/Controllers/DeliveryOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ADProjGp2_LogicUStationeryStore.BusinessLogic;
using ADProjGp2_LogicUStationeryStore.Models;

namespace ADProjGp2_LogicUStationeryStore.Controllers
{
    public class DeliveryOrderController : Controller
    {
        DeliveryOrderBusinessLogic deliverBizLogic = new DeliveryOrderBusinessLogic();

        [HttpPost]
        public ActionResult DeliveryOrderEntry(string PONumber)
        {
            DeliverOrderViewModel dovm = deliverBizLogic.DeliveryOrderEntryPreparation(PONumber);
            return View(dovm);
        }

        [HttpPost]
        public ActionResult DeliveryOrderEntryConfirm(DeliverOrderViewModel dovm)
        {          
            return View(dovm);
        }

        [HttpPost]
        public ActionResult DeliveryOrderEntrySubmission(DeliverOrderViewModel dovm)
        {
            dovm = deliverBizLogic.DeliverOrderMatching(dovm);
            deliverBizLogic.DeliveryConfirmation(dovm);
            return RedirectToAction("PurchaseOrderList", "Purchase");
        }

        public ActionResult DeliveryOrderList()
        {
            SSISEntities db = new SSISEntities();
            List<DeliveryOrder> deliverList = db.DeliveryOrders.ToList();
            return View(deliverList);
        }
    }
}

ADProjGp2_LogicUStationeryStore/Views/DeliveryOrder/DeliveryOrderEntry.cshtml
@{
    ViewBag.Title = "DeliveryOrderEntry";
}

@model ADProjGp2_LogicUStationeryStore.Models.DeliverOrderViewModel
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DeliveryOrderEntry</title>
    <link href="~/Content/css/Button-Antiman.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/css/Requisition.css" rel="stylesheet" type="text/css" />
    <style>
        .infoTable {
            border-collapse: initial;
        }

            .infoTable tr td {
                font-weight: 800;
            }

                .infoTable tr td span {
                    font-weight: 300;
                }

        .listTable thead, table tr {
            border-top-width: 1px;
            border-top-style: solid;
            border-top-color: #808080;
        }

        .listTable tbody th {
            background-color: #d6dfe5;
            padding-left: 10px;
        }

        .listTable tbody td {
            padding-left: 8px;
            padding-right: 8px;
        }

        .listTable {
            border-bottom-width: 1px;
            border-bottom-style: solid;
            border-bottom-color: #808080;
            table-layout: fixed;
            border-collapse: collapse;
        }
    </style>
</head>
<body>
    <div class="panel-body" style="padding-bottom:0px;min-width:400px;">
        <div class="panel panel-default">
            <div class="panel-heading" style="min-width:400px;text-align:center;font-size:25px">Delivery Order</div>
            <div class="panel-body">
                @using (@Html.BeginForm())
                {
                    <div>
                        <table style="min-width:860px;" class="infoTable">
                            <tr>
                                <td><h3 style="text-align:left;padding-left:0;">PO Reference: <span>@Model.poNumber</span></h3></td>
                                <td><h3>PO Date: <span>@Model.orderDate</span></h3></td>
                                <td style="width:120px;"><h3>Clerk ID: <span>@Model.clerkID</span></h3></td>
                                <td><h3>Supplier ID: <span>@Model.supplierID</span></h3></td>
                                <td><h3>Order Remark: <span>@Model.orderRemark</span></h3></td>

                                @Html.HiddenFor(m => m.orderRemark)
                                @Html.HiddenFor(m => m.poNumber)
                                @Html.HiddenFor(m => m.orderDate)
                                @Html.HiddenFor(m => m.clerkID)
                                @Html.HiddenFor(m => m.supplierID)
                                @Html.HiddenFor(m => m.status)
                            </tr>

                            <tr>
                                <td colspan="3"><h3 style="text-align:left;padding-left:0;">DO Reference: <input type="text" placeholder="Please enter Delivery Order Number" id="doNumber" name="doNumber" size="50" required /></h3></td>
                                <td colspan="2"><h3 style="text-align:left;padding-left:0;">DO Date: <input type="date" id="doDate" name="doDate" required /></h3></td>
                                @Html.HiddenFor(m => m.doDate)
                                @Html.HiddenFor(m => m.doNumber)
                            </tr>
                            <tr>
                                <td colspan="5" height="70px;"><h3 style="vertical-align:central;text-align:left;padding-left:0;">Delivery Order Remarks: </h3><textarea name="deliverRemark" rows="3" cols="50" placeholder="Remarks..."></textarea></td>
                                @Html.HiddenFor(m => m.deliverRemark)
                            </tr>
                        </table>
                    </div>
                    <br />
                    <br />
                    <div>
                        <table class="listTable" style="min-width:860px;">
                            <tr>
                                <th>Item ID</th>
                                <th>Purchase Qty</th>
                                <th>Deliver Qty</th>
                                <th>Remark</th>
                            </tr>

                            @for (int i = 0; i < Model.dovmdList.Count; i++)
                {
                                <tr>
                                    <td>
                                        @Model.dovmdList[i].itemNumber - @Model.dovmdList[i].itemDescription (@Model.dovmdList[i].itemUOM)
                                    </td>
                                    @Html.HiddenFor(m => m.dovmdList[i].itemNumber)
                                    @Html.HiddenFor(m => m.dovmdList[i].itemDescription)
                                    @Html.HiddenFor(m => m.dovmdList[i].itemUOM)
                                    <td>@Model.dovmdList[i].purchaseQty</td>
                                    @Html.HiddenFor(m => m.dovmdList[i].purchaseQty)
                                    @if (Model.dovmdList[i].IsMatched == true)
                                    {
                                        <td>@Model.dovmdList[i].deliverQty</td>
                                        @Html.HiddenFor(m => m.dovmdList[i].deliverQty)
                                    }
                                    else
                                    {
                                        <td>@Html.EditorFor(m => m.dovmdList[i].deliverQty)</td>
                                        @Html.HiddenFor(m => m.dovmdList[i].deliverQty)
                                    }
                                    <td>@Model.dovmdList[i].remark</td>
                                    @Html.HiddenFor(m => m.dovmdList[i].remark)
                                    @Html.HiddenFor(m => m.dovmdList[i].podID)
                                    @Html.HiddenFor(m => m.dovmdList[i].IsMatched)

                                </tr>

                            }
                        </table>
                    </div>
                    <br />
                    <div class="button-container">
                        <a href="~/Purchase/PurchaseOrderDetail" class="button button--size-m button--antiman button--round-m button--text-medium">Back</a>
                        <button type="submit" class="button button--size-m button--antiman button--round-m button--text-medium" formaction=@Url.Action("DeliveryOrderEntryConfirm", "DeliveryOrder") formmethod="post">Review Delivery Order Submission</button>
                    </div>
                }
            </div>
        </div>
    </div>
</body>
</html>

ADProjGp2_LogicUStationeryStore/Views/DeliveryOrder/DeliveryOrderEntryConfirm.cshtml
@{
    ViewBag.Title = "DeliveryOrderEntry";
}

@model ADProjGp2_LogicUStationeryStore.Models.DeliverOrderViewModel
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DeliveryOrderEntryConfirm</title>
    <link href="~/Content/css/Button-Antiman.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/css/Requisition.css" rel="stylesheet" type="text/css" />
    <style>
        .infoTable {
            border-collapse: initial;
        }

            .infoTable tr td {
                font-weight: 800;
            }

                .infoTable tr td span {
                    font-weight: 300;
                }

        .listTable thead, table tr {
            border-top-width: 1px;
            border-top-style: solid;
            border-top-color: #808080;
        }

        .listTable tbody th {
            background-color: #d6dfe5;
            padding-left: 10px;
        }

        .listTable tbody td {
            padding-left: 8px;
            padding-right: 8px;
        }

        .listTable {
            border-bottom-width: 1px;
            border-bottom-style: solid;
            border-bottom-color: #808080;
            table-layout: fixed;
            border-collapse: collapse;
        }
    </style>
</head>
<body>
    <br />
    <div class="panel-body" style="padding-bottom:0px;min-width:400px;">
        <div class="panel panel-default">
            <div class="panel-heading" style="min-width:400px;text-align:center;font-size:25px">Delivery Order Confirm</div>
            <div class="panel-body">
                @using (@Html.BeginForm())
                {
                    <div>
                        <table style="min-width:860px;" class="infoTable">
                            <tr>
                                <td><h3 style="text-align:left;padding-left:0;">PO Reference: <span>@Model.poNumber</span></h3></td>
                                <td><h3>PO Date: <span>@Model.orderDate</span></h3></td>
                                <td><h3>Clerk ID: <span>@Model.clerkID</span></h3></td>
                                <td><h3>Supplier ID: <span>@Model.supplierID</span></h3></td>
                                <td><h3>Supplier ID: <span>@Model.orderRemark</span></h3></td>

                                @Html.HiddenFor(m => m.orderRemark)
                                @Html.HiddenFor(m => m.poNumber)
                                @Html.HiddenFor(m => m.orderDate)
                                @Html.HiddenFor(m => m.clerkID)
                                @Html.HiddenFor(m => m.supplierID)
                            </tr>
                            <tr>
                                <td colspan="3"><h3 style="text-align:left;padding-left:0;">DO Reference: <span>@Model.doNumber</span></h3></td>
                                <td colspan="2"><h3 style="text-align:left;padding-left:0;">DO Date: <span>@Model.doDate</span></h3></td>
                                @Html.HiddenFor(m => m.doDate)
                                @Html.HiddenFor(m => m.doNumber)
                            </tr>
                            <tr>
                                <td colspan="5"height="70px;"><h3 style="vertical-align:central;text-align:left;padding-left:0;">DO Remarks: </h3><span>@Html.TextAreaFor(m => m.deliverRemark, new { @rows = "3", @cols = "50", @readonly = true })</span></td>
                                @Html.HiddenFor(m => m.deliverRemark)
                            </tr>
                        </table>
                    </div>
                    <br />
                    <br />
                    <div>
                        <table class="listTable" style="min-width:860px;">
                            <tr>
                                <th>Item ID</th>
                                <th>Purchase Qty</th>
                                <th>Deliver Qty</th>
                                <th>Remark</th>
                            </tr>
                            @for (int i = 0; i < Model.dovmdList.Count; i++)
                            {
                                <tr>
                                    <td id="colBin">@Model.dovmdList[i].itemNumber - @Model.dovmdList[i].itemDescription (@Model.dovmdList[i].itemUOM)</td>
                                    @Html.HiddenFor(m => m.dovmdList[i].itemNumber)
                                    @Html.HiddenFor(m => m.dovmdList[i].itemDescription)
                                    @Html.HiddenFor(m => m.dovmdList[i].itemUOM)
                                    <td id="colQuantity">@Model.dovmdList[i].purchaseQty</td>
                                    @Html.HiddenFor(m => m.dovmdList[i].purchaseQty)
                                    <td id="colQuantity">@Model.dovmdList[i].deliverQty</td>
                                    @Html.HiddenFor(m => m.dovmdList[i].deliverQty)
                                    <td id="colQuantity">@Model.dovmdList[i].remark</td>
                                    @Html.HiddenFor(m => m.dovmdList[i].remark)
                                    @Html.HiddenFor(m => m.dovmdList[i].podID)
                                    @Html.HiddenFor(m => m.dovmdList[i].IsMatched)
                                </tr>
                            }
                        </table>
                    </div>
                    <div class="button-container">
                        <a href="~/DeliveryOrder/DeliveryOrderList" class="button button--size-m button--antiman button--round-m button--text-medium">Cancel</a>
                        <button type="submit" class="button button--size-m button--antiman button--round-m button--text-medium" value="DeliverOrderEntry" name=DeliverOrderEntry formaction=@Url.Action("DeliveryOrderEntrySubmission", "DeliveryOrder") formmethod="post">Submit Delivery Order</button>
                    </div>
                }
            </div>
        </div>
    </div>
</body>
</html>

ADProjGp2_LogicUStationeryStore/Views/DeliveryOrder/DeliveryOrderList.cshtml
@{
    ViewBag.Title = "DeliveryOrderList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model List<ADProjGp2_LogicUStationeryStore.DeliveryOrder>
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DisbursementListDetail</title>
    <link href="~/Content/css/Button-Antiman.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/css/Requisition.css" rel="stylesheet" type="text/css" />
    <style>
        #RDlist th {
            word-break: keep-all;
        }

        table thead, table tr {
            border-top-width: 1px;
            border-top-style: solid;
            border-top-color: #808080;
        }

        table tbody th {
            background-color: #d6dfe5;
        }

        table {
            border-bottom-width: 1px;
            border-bottom-style: solid;
            border-bottom-color: #808080;
            table-layout: fixed;
        }
    </style>

</head>
<body>
    <div>
        <h1>Delivery Order List</h1>
        @using (@Html.BeginForm())
        {
            <div>
                <table id="RDlist" style="min-width:840px;">
                    <tr>
                        <th>Delivery Order ID </th>
                        <th>Purchase Order ID</th>
                        <th>Delivery Date</th>
                        <th>Remark</th>
                    </tr>
                    @for (int i = 0; i < Model.Count; i++)
                    {
                    <tr>
                        <td>@Model[i].doId</td>
                        @Html.HiddenFor(m => m[i].doId)
                        <td>@Html.ActionLink(Model[i].poId, "PurchaseOrderDetail", "Purchase",new { id = Model[i].poId}, new { @style = "text-decoration:underline;" })</td>
                        @Html.HiddenFor(m => m[i].poId)
                        <td>@Model[i].deliveryDate</td>
                        @Html.HiddenFor(m => m[i].deliveryDate)
                        <td>@Model[i].remark</td>
                        @Html.HiddenFor(m => m[i].remark)
                    </tr>
                    }
                </table>
            </div>
        }
    </div>
</body>
</html>